version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - kai0310
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 8.26.0
    - 8.28.0
    - 8.30.0
    - 8.30.1
    - 8.31.0
    - 8.32.0
    - 8.33.0
    - 8.33.1
    - 8.34.0
    - 8.35.0
    - 8.35.1
    - 8.36.0
    - 8.36.1
    - 8.37.0
    - 8.38.0
    - 8.39.0
  - dependency-name: nunomaduro/collision
    versions:
    - 5.4.0
  - dependency-name: fakerphp/faker
    versions:
    - 1.14.0
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.3.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.3
    - 9.5.4
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - kai0310
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.12
  - dependency-name: tailwindcss
    versions:
    - 2.1.0
