name: composer update

on:
  schedule:
    - cron: '0 4 * * *' #UTC

jobs:
  composer_update_job:
    runs-on: ubuntu-latest
    name: composer update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: composer update action
        uses: kai0310/composer-update-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_NAME: kai0310
          GIT_EMAIL: kn0310@outlook.jp
          REVIEWERS: "kai0310"
